pop-os/distinst

src/c.rs, src/chroot.rs, src/configure.sh, src/disk/mod.rs, src/disk/mounts.rs, src/disk/operations.rs, src/disk/partitions.rs, src/format.rs, src/lib.rs, src/logger.rs, src/main.rs, src/mount.rs, src/partition.rs, src/squashfs.rs
Users can currently define the target mount point of a partition, but are not yet able to have that information carried over in the install. This PR will aim to implement fstab generation within distinst, where each entry will have a UUID obtained from symlink resolutions in `/dev/disk/by-uuid`, and targets provided by the installer will be written to `/etc/fstab` by distinst.
=> Implement fstab Generation

src/disk/external.rs, src/envfile.rs, src/lib.rs, src/scripts/configure.sh
- Modifies the `configure.sh` file to add `OEM_MODE=0`
- If `/cdrom/recovery.conf` exists, remount `/cdrom` with the `rw` option
- Then update the value of `OEM_MODE` to `0`
- And also update the value of `ROOT_UUID` to the new value
This code has not yet been tested.
=> Set OEM flags in recovery configuration

src/disk/config/disk.rs, src/disk/config/disk_trait.rs, src/disk/config/disks.rs, src/disk/config/lvm/deactivate.rs, src/disk/config/lvm/detect.rs, src/disk/config/lvm/mod.rs, src/disk/config/mod.rs, src/disk/config/partitions/mod.rs, src/disk/external.rs, src/disk/operations/mod.rs
Replaces most usages of `unwrap()` with `expect()`, to get more information in the event that an option is unwrapped.
=> unwrap() -> expect()

src/disk/config/lvm/mod.rs, src/disk/external.rs
Fixes https://github.com/pop-os/pop/issues/272
Logical devices with dashes in their name will have their paths modified to use two dashes instead of one, although they'll still be referred to by their single dash name within LVM tools. This will fix the device paths to account for that.
=> Fix for logical devices with dashes in names

src/hardware_support/macros.rs, src/hardware_support/mod.rs, src/hardware_support/modules.rs
Detects if the `nvidia` module is loaded, and if so, selects the `system76-driver-nvidia` package for install when the install media has `Pop!_OS` as the `NAME` in `/etc/os-release`. Otherwise, `nvidia-driver-390` for media with an `ID_LIKE` of `debian`.
The package macros were slightly modified to be more flexible, due to Pop!-specific handling.
This compiles, and I have tested it to work.
=> Detect nvidia module & append nvidia package

cli/src/main.rs, src/disk/mod.rs, src/lib.rs
- The backend will now have a switch that will override `Bootloader::detect()` to return `Bios`.
- The cli now has a `--force-bios` flag that will set this value.
@jackpot51
=> Add FORCE_BIOS Bootloader switch

src/disk/config/disk.rs, src/disk/config/disk_trait.rs, src/disk/config/lvm/mod.rs, src/disk/config/partitions/mod.rs, src/disk/error.rs, src/disk/mod.rs, tests/install-bios.sh
- When primary partitions have been exceeded, switch them to logical
- If an extended partition does not yet exist, create it automatically
With this change, it will no longer be required to manually specify an extended partition, and it will no longer be required to specify a partition as logical.
=> Automatically create extended partition

src/disk/config/disk.rs, src/disk/external.rs
- Prevents swap partitions from having their UUIDs changed.
- Useful to prevent UUIDs being changed out in a dual boot configuration.
Tested with the bios-install script, running `lsblk` before and after.
```sh
sudo target/debug/distinst \
-s "${FS}" \
-r "${REMOVE}" \
-h "pop-testing" \
-k "us" \
-l "en_US.UTF-8" \
--force-bios \
-b "$1" \
-u "$1:2:ntfs:mount=/win" \
-u "$1:3:ext4:mount=/" \
-u "$1:6:ext4:mount=/home" \
-u "$1:7:swap"
```
Partitions 2, 3, 6, and 7 were marked to be reformatted.
```
NAME   FSTYPE LABEL              UUID                                 MOUNTPOINT
sdb                                                                   
├─sdb1 ntfs                      264DD6AD20E2DAA7                     
├─sdb2 ntfs                      264DD6AD20E2DAA7 …
```
=> Don't overwrite swap partitions with swap

ffi/distinst.vapi, ffi/src/disk.rs, ffi/src/lvm.rs, src/auto/options/mod.rs, src/disk/config/disk.rs, src/disk/config/disk_trait.rs, src/disk/config/disks.rs, src/disk/config/lvm/mod.rs, src/disk/config/mod.rs, src/lib.rs
Removes a possible source of instability that could cause a crash.
This could cause a crash when the parent Disks struct is moved due to move semantics.
Requires slight API change to the C FFI.
=> Remove cyclic reference to parent disks

src/disk/config/disks.rs, src/scripts/configure.sh
Fixes the following issue:
1. Do a clean install
2. Do a custom install to reinstall, but do not format `/`, and do not set a mount for `/recovery`
It will fail, because the /recovery directory exists, but has no device mounted to it.
=> Only attempt to apply recovery changes when the recovery partition exists

ffi/distinst.vapi, src/chroot.rs
This way, if the installer hangs while on the `configure.sh`, or has an error, that error should be reported in the installer UI's logs. Logs shouldn't be required to be obtained from the terminal.
=> Log chroot outputs to installer logs

ffi/distinst.vapi, ffi/src/lvm.rs, src/disk/config/disks.rs, src/disk/config/lvm/deactivate.rs, src/disk/external.rs, src/lib.rs
- Can enable the front end to start with all encrypted devices closed
- Can also be used to deactivate devices when exiting from a custom partitioning screen
- Fixes a logic error that may delete the PVs & VGs when reinstalling onto an existing PV & VG.
=> Add function for deactivating all opened encrypted devices

src/misc.rs
Noticed within the installer that the CPU usage was consistently over 200% (two full cores), due to an endless loop of reads. This will fix that.
=> Cut CPU usage by 200% while idling

Cargo.lock, Cargo.toml, examples/default_install.rs, src/auto/options/apply.rs, src/auto/options/mod.rs, src/disk/config/disk.rs, src/disk/config/partitions/usage.rs, src/disk/mounts.rs, src/disk/serial.rs, src/disk/swaps.rs, src/distribution/debian.rs, src/hardware_support/modules.rs, src/lib.rs, src/scripts/configure.sh, src/state.rs
Made some changes to remove a complex macro from the `Installer::install()` function. Encrypted installations with `grub-efi` are now possible, as well.
=> Encrypted Ubuntu Installations

Cargo.lock, Cargo.toml, debian/control, ffi/distinst.vapi, ffi/src/dbus.rs, ffi/src/lib.rs, src/dbus_interfaces/logind.rs, src/dbus_interfaces/mod.rs, src/lib.rs
UIs will no longer need to write their own code to inhibit suspension on systemd systems.
Vala example:
```vala
int pipe_fd = Distinst.session_inhibit_suspend ();
if (pipe_fd == -1) {
stderr.printf ("failed to inhibit suspension\n");
}
// Any attempt to suspend after this point will fail
// and/or request the user to unlock the inhibitor.
do_things ();
// At a later point, when the caller wants to unlock the inhibitor:
Posix.close (pipe_fd);
```
=> Support interaction with the dbus systemd login1 manager

ffi/distinst.vapi, ffi/src/disk.rs, ffi/src/partition.rs, src/disk/config/disk_trait.rs, src/disk/config/disks.rs
- Allows the caller to get the partition table of a disk to determine if an EFI partition on that disk is a valid configuration.
- Additionally checks itself before installing to see if the provided input is correct.
=> EFI GPT Checks

src/lib.rs
Invoke `sync()` before unmounting the chroot in the configure step.
=> installer/steps/configure: sync before unmounting

src/process/chroot/configure.rs
Changes the net resolv link to  `"../run/systemd/resolve/stub-resolv.conf"`
=> Change the resolv.conf link for 18.10

src/distribution/debian.rs, src/installer/steps/configure.rs
- The new manifest-remove includes `cryptsetup-{initramfs,run}` now.
- Added an additional check to `debian::get_required_packages()` to retain them.
Closes #150
=> Fix encrypted installs on 18.10

src/process/command.rs
- The original I/O error kind will now be forwarded
- Adds unit tests to ensure that the behavior works
- Fixes BIOS installations
=> Fix `Command::run()` to retain the `NotFound` error kind

src/process/chroot/configure.rs
If the EFI or recovery partition have the same UUID, one of these will return `None` for a UUID. This will attempt to account for that when it happens. The recovery UUID is used to compare against the cdrom UUID. Will look for a better solution soon. It's also used for setting the name of the `casper-XXX` and `Recovery-XXX` directories.
=> Fix UUID comparison function in chroot::configure

src/installer/steps/bootloader.rs
This should fix trubble imaging of Ubuntu
=> Do not set nvram variables when using grub-install, as this is done later with efibootmgr

Cargo.lock, Cargo.toml, crates/disk-ops/Cargo.toml, crates/disks/Cargo.toml, crates/disks/src/config/disk.rs, crates/external/Cargo.toml, ffi/distinst.vapi, ffi/src/disk.rs, src/auto/options/mod.rs
Devices like `/dev/sr0` will no longer appear as an erase option, due to their read-only status.
=> Hide read-only devices from install options

src/installer/steps/configure/chroot_conf.rs
When two UUIDs are the same, there's a risk that casper will not be able to find the block device with the specified casper directory. Testing found that the only way to get the recovery partition to boot was to set `live-media=/dev/disk/by-partuuid/${PARTUUID}` as one of the kernel options, to avoid the scan entirely.
@brs17 Testing this should be as simple as seeing if an install works with differing UUIDs, and if it also works when they are the same.
=> Casper cannot find the recovery partition if there's a duplicate UUID

src/distribution/debian.rs
This fixes installing Ubuntu 18.04.2 with distinst. Regression potential extremely low, and only affects imaging systems using Ubuntu. I am looking to get this out ASAP so Ubuntu imaging can be re-enabled.
=> Add correct kernel for Ubuntu 18.04

src/installer/steps/configure/chroot_conf.rs
Fixes #207 
This doesn't fail if a package in the list isn't installed. For example, see the following terminal output:
```
david@david-XPS-13-9343:~/Documents/Projects/appcenter/build$ sudo dpkg --purge fakepackagename
dpkg: warning: ignoring request to remove fakepackagename which isn't installed
david@david-XPS-13-9343:~/Documents/Projects/appcenter/build$ echo $?
0
david@david-XPS-13-9343:~/Documents/Projects/appcenter/build$ sudo apt-get purge -y fakepackagename
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fakepackagename
david@david-XPS-13-9343:~/Documents/Projects/appcenter/build$ echo $?
100
```
=> Use dpkg instead of apt-get for package purging

src/distribution/debian.rs
`fwupdate-signed` is now `fwupd-signed` and it appears the signed kernel is just called `linux-image-generic`. Signed kernels have become the default and unsigned kernels are now available with `linux-image-generic-unsigned`.
=> Add support for Ubuntu 20.04

Cargo.lock, Cargo.toml, ffi/distinst.vapi, ffi/src/lib.rs, src/distribution/debian.rs, src/installer/steps/configure/chroot_conf.rs, src/installer/steps/configure/mod.rs, src/lib.rs
Alternative fix for #207 
https://github.com/pop-os/distinst/commit/650984da73ddf7f4b44d024fb5d80503529305e3 should probably be reverted as it is causing dependency issues in our 20.04 test builds
=> Only remove kernelstub on Pop!_OS

src/installer/traits.rs
Matches https://github.com/pop-os/upgrade/pull/126.
This should change no behavior (other than warnings) since 'plain' is the default.
=> fix: Specify 'plain' in cryptswap line of /etc/crypttab

src/distribution/debian.rs
This fixes creating Ubuntu 20.04 images
=> Use HWE kernel on Ubuntu 20.04

src/distribution/debian.rs
Question before merging:
Why are `fwupd-signed` and `linux-image-generic` in the list of packages for the bootloader here? This was originally copied from the Ubuntu 18.04 code, but surely the kernel and fwupd already exist in the squashfs which gets deployed to the install, so why install them again at the bootloader stage?
We're happy to give this a test with those packages removed as it means less changes needed here if we want to switch to a different kernel package for HWE or w/e.
=> fix: Be less strict about elementary OS versions

Cargo.lock, crates/hardware/Cargo.toml, crates/hardware/src/switchable_graphics.rs
Make check for switchable graphics generic by calling `com.system76.PowerDaemon.GetSwitchable`, which uses PCI enumeration to determine support.
Limit the result to System76 models due to causing problems on other vendor's machines in the past.
=> Dynamically determine switchable graphics

Cargo.lock, crates/locales/Cargo.toml, crates/locales/src/iso3166_1.rs, crates/locales/src/iso_codes.rs, crates/locales/src/lib.rs, debian/control
The `iso3166-1` crate seems to be outdated and unmaintained. Debian packages data files with the necessary information, and `distinst` already depends on various Debian packages, so it's probably better to use that.
This fixes https://github.com/pop-os/distinst/issues/240 as well addressing failures to translate where the string from the `iso3166-1` crate was not in the gettext translation data.
This can be tested with `cargo run --example locale` and with `pop-installer`.
=> fix: Use iso-codes package and 'common_name'

Cargo.lock, crates/locales/Cargo.toml, crates/locales/src/iso639.rs, crates/locales/src/iso_codes.rs, crates/locales/src/lib.rs
This fixes the issue where "ber" wasn't mapped to any name, and showed up as a blank link at the end of the language list in the installer. Now it is listed as Berber "languages".
=> fix: Use iso-codes package for languages

src/installer/steps/bootloader.rs
Systems with secure boot enabled can't load grub directly as it isn't signed with a Microsoft key. They first have to load the shim.
=> Support secure boot in non Pop!_OS distributions

Cargo.lock, crates/disk-ops/src/mkpart.rs, crates/disk-types/Cargo.toml, crates/disk-types/src/device.rs, crates/disk-types/src/lib.rs, crates/disk-types/src/partition.rs, crates/disk-types/src/sector.rs, crates/disk-types/src/utils.rs, crates/disks/src/config/disk.rs, crates/disks/src/config/disks.rs, crates/disks/src/config/lvm/mod.rs, crates/disks/src/config/partitions/mod.rs, crates/external/src/lvm.rs, src/auto/options/mod.rs, src/installer/steps/configure/chroot_conf.rs
- Fix a panic caused by code not getting the correct path for the parent of a partition block device
- Fixed another panic caused by the probing the contents of CD ROM, which should never be an install target
=> Fixes for recent regressions in disk probing

cli/src/main.rs, ffi/distinst.vapi, ffi/src/lib.rs, src/installer/mod.rs, src/installer/steps/configure/chroot_conf.rs, src/installer/steps/configure/mod.rs
Fixes #228 
This probably isn't great code; I'm only very beginner level with Rust. Feel free to refactor at will.
I've tested that this works with the `distinst` CLI. Passing the new `--run-ubuntu-drivers` option allows it to install the proprietary `bcmwl-kernel-source` driver for my WiFi chipset from the apt-cdrom repository on an elementary iso when it normally wouldn't.
=> feat: Use ubuntu-drivers to find drivers and install

src/installer/steps/configure/chroot_conf.rs
Because `useradd` defaults the shell to `/bin/sh` in `/etc/default/useradd`.
Required by https://github.com/pop-os/installer/pull/219
=> fix(user-create): Set default shell as /bin/bash

crates/external/src/block.rs
Reverts pop-os/distinst#270. This change may have caused grub-install to stop working.
=> Revert "Activate casefolding feature by default (without chattr)"

src/distribution/debian.rs
We've started building Ubuntu 22.04 based images and `grub-efi` no longer exists in Ubuntu `jammy`. It was always just a dummy package that pulled in `grub-efi-amd64` anyway. Dropping this here will stop installation failures due to that package not existing.
=> debian: Drop grub-efi dependency for elementary

ffi/distinst.vapi
Using Vala 0.54 with this vapi file results in the following error:
```
distinst.vapi:683.9-683.27: error: [SimpleType] struct `Distinst.SectorResult' cannot have owned heap-allocated fields
public string error;
```
`SimpleType` should only be used for stack allocated structures, usually just when a builtin type gets typedef'ed to something in C. Since distinst doesn't manage the lifetime of this structure, we can remove the `SimpleType` and let Vala generate a destroy function for it to clean up the strings left on the heap.
As far as I can tell, this structure or the `from_str` method that returns it isn't used in either the elementary or Pop!_OS version of the installer, so the chance of regressions here should be low.
=> chore(vapi): Fix compilation with Vala 0.54

src/installer/steps/bootloader.rs, src/installer/steps/configure/chroot_conf.rs, src/installer/steps/configure/mod.rs
This will symlink `/usr/sbin/update-initramfs` to `/usr/bin/true` while the system is being configured, until the final stage wher update-initramfs is manually called for at the end of the bootloader installation.
Fixes #282
=> feat: Disable update-initramfs until the installer is ready for it

src/installer/steps/configure/chroot_conf.rs
Propagates these possible errors rather than panicking.
Should close #285, to be clear this PR doesn't prevent the install from failing, but the user should get an error rather than the installer just crashing
=> Propogate some more errors

Cargo.lock, crates/hardware/Cargo.toml, crates/hardware/src/lib.rs, debian/control
This adds support for building distinst for non-x86(_64) targets, mainly arm64.
Builds fine for me, re-made PR because CI is very picky about branch names
=> Non-x86 support 

crates/external/src/block.rs
=> fix: Use blkid to get label value for other file systems

crates/disks/src/config/partitions/mod.rs, crates/external/src/block.rs
This PR changes preferred options for f2fs.
This set of options was inspired by ArchLinux's [recommended options](https://wiki.archlinux.org/title/F2FS#Recommended_mount_options) with some changes.
- **compress_algorithm=lz4** - compression by itself is useful to prolong flash drive life. The trouble I had was to figure out what algorithm to use for desktop usage. There are several options, generally (from what I managed to find) people tend to use either [zstd](https://github.com/facebook/zstd) or [lz4](https://github.com/lz4/lz4) for filesystem compression.
Judging by [this benchmark](https://indico.fnal.gov/event/16264/contributions/36466/attachments/22610/28037/Zstd__LZ4.pdf) lz4 is faster at (de)compression but has a lower compression ratio. My thinking here is that this will be less …
=> f2fs: change preferred options

crates/external/src/block.rs
This is a continuation of #296, there was a request in the discussion section to use `-f` option but that PR was accepted before I managed to make the changes.
=> f2fs: use force overwrite switch

crates/fstab-generate/src/block.rs
Issue: https://github.com/pop-os/distinst/issues/312
Following Ubuntu, Arch, and general best practices for generating fstab entries the root partition should be set to fsck with highest priority. This pull request will set the root partition fsck entry to 1. 
Here's some documentation around fstab values
https://help.ubuntu.com/community/Fstab
https://wiki.archlinux.org/title/fstab
I feel there's some room here for supporting customization and I would be happy to expand on this, but this will be a good starting point to address users concerns
=> Schedule fsck on root partition

src/installer/steps/configure/chroot_conf.rs
This feature was added by me in #255 but it is desirable that we don't fail the whole installation process if an optional driver fails to install.
=> Don't hard fail on failed driver installation

src/installer/steps/configure/chroot_conf.rs
Coming from here https://github.com/elementary/os/issues/686#issuecomment-1697587704
`ubuntu-drivers list` returns a list of 9 Nvidia drivers in Ubuntu 22.04 and elementary OS 7. However, we only want to install one of them. With `--recommended`, only the most recent driver will be listed.
Committed from the GitHub web UI, I don't have a development environment for this right now.
=> Only install --recommended drivers

src/installer/steps/configure/chroot_conf.rs
Follow-up to #320, based on discussion here https://github.com/elementary/os/issues/686#issuecomment-1710730849
"ubuntu-drivers" uses different separators when passing the "--recommended" flag, so the current `split(",")` breaks when more than one package name is being returned. This PR adjusts the code so that multi-package and multi-line output can both be parsed correctly.
=> Fix parsing of "ubuntu-drivers list --recommended" output

src/installer/steps/configure/chroot_conf.rs
systemd-resolved resolves localhost and the hostname by default; libnss-myhostname additionally takes care of this. Creating the file leads to problems if hostnamectl is used to update the hostname later, since the file is not updated by that tool. Ref: https://github.com/pop-os/systemd/issues/5 
I wasn't sure if there might still be a reason to keep the function around. I removed it since this was the only place it was used, but engineering feedback is welcome on that.
=> fix: Stop populating hostname in /etc/hosts by default

crates/disks/src/config/disks.rs, src/auto/options/apply.rs, src/auto/options/mod.rs
This is to debug an issue currently seen with our latest ISOs. This will add some extra logs to display the partition that failed to be applied for the refresh config, a dump of `lsblk` before applying the config, and a delay of 3 seconds before getting a list of volumes after a decrypted PV is online.
=> Fix detection of missing encrypted partitions
