.github/ISSUE_TEMPLATE.md

Adding and updating ISSUE_TEMPLATE used throughout Pop!_OS projects

Adding ISSUE_TEMPLATE used throughout Pop!_OS

---

src/squashfs.rs

Fix progress when launching installer from desktop icon by using PTY to communicate with unsquashfs.

Use PTY to communicate with unsquashfs

---

src/disk/config/disks.rs
src/lib.rs

This fixes BIOS installs with LVM

If /boot is a seperate partition, install bootloader there

---

Cargo.lock
Cargo.toml
cli/src/main.rs
ffi/distinst.vapi
ffi/src/lib.rs
src/lib.rs
tests/install.sh

This installs the following, if detected and INSTALL_HARDWARE_SUPPORT is passed:
- amd64-microcode
- intel-microcode
- system76-driver

Add hardware support packages

---

src/lib.rs

Unsure on what we want as the name of the EFI entry, so I've put `Linux Boot Manager (systemd-boot)` for now.

Use efibootmgr to set boot order

---

cli/src/main.rs

- The `--test` flag will now simply set PARTITIONING_TEST, which will not install
- A new `--modify-boot` flag will have the installer modify the boot order
- A new `--hardware-support` flag will have the installer install hardware support packages
- MODIFY_BOOT_ORDER and INSTALL_HARDWARE_SUPPORT are disabled by default
@jackpot51

Add additional test flags

---

examples/luks.rs
ffi/distinst.vapi
ffi/src/disk.rs
ffi/src/lvm.rs
ffi/src/partition.rs
src/disk/config/disk.rs
src/disk/config/disk_trait.rs
src/disk/config/disks.rs
src/disk/config/lvm/mod.rs
src/disk/config/mod.rs
src/disk/external.rs
src/lib.rs

- Ability to decrypt and install to LUKS devices that have a file system other than LVM.
- Physical and logical devices may now have file systems
- Additional error handling for detecting LUKS partitions (should be no more cases of a LUKS partition being detected as `none`)
- Also includes some C API changes to make it more convenient for the Vala frontend to detect if encrypted partitions exist, and whether or not a certain partition is encrypted or not.

LUKS Improvements

---

debian/control
ffi/distinst.vapi
ffi/src/filesystem.rs
src/disk/config/partitions/mod.rs
src/disk/external.rs

Disable ExFAT support, due to patents

---

Makefile
src/chroot.rs
src/lib.rs
src/scripts/configure.sh

This will prevent the host system from having a system crash on the second installation attempt.
Closes #123

Better localectl fix

---

src/hardware_support/macros.rs
src/hardware_support/mod.rs
src/lib.rs
src/scripts/configure.sh

Copy a missing kernel from the cdrom, if it is missing

---

src/scripts/configure.sh

This is critical for trubble, so I would like it merged ASAP
The change has nearly no potential for regression

Add sync after configure.sh

---

src/disk/config/disk.rs
src/disk/config/partitions/mod.rs
src/installer/steps/initialize.rs
src/misc.rs

@brs17 This should fix the swap error, where an already deactivated swap device errors when deactivating it.

Fix error on deactivating deactive swap partitions

---

Cargo.lock
Cargo.toml
src/lib.rs
src/misc.rs
src/process/chroot/configure.rs

It was just a copy/paste of the enable method
Closes #148

Fix ChrootConfigure::apt_cdrom_disable

---

src/auto/options/apply.rs
src/auto/options/recovery_option.rs
src/envfile.rs

The issue seems to only happen on an encrypted install. Unsure on the cause yet. Currently testing.

WIP: Fix recovery on encrypted install

---

src/disk/config/partitions/mod.rs

This does not change or modify any code used by the installer. This will merely provide an additional useful method for the pop-recovery tool, when using distinst to probe for the recovery partition.

Add PartitionInfo::probe() for API callers

---

src/misc.rs

Ubuntu has an older rustc, and impl Trait is not available

Fix Ubuntu 18.04 build

---

crates/hardware/src/blacklist.rs

Add gaze14 to SWITCHABLE_GRAPHICS

---

crates/hardware/src/blacklist.rs

Add addp1 to SWITCHABLE_GRAPHICS

---

debian/control
ffi/src/partition.rs

This should still build on other series as well

Fix build for focal

---

src/lib.rs

fix: BIOS minimum disk size will no longer account for EFI partition requirements

---

crates/chroot/src/command.rs
crates/disk-ops/src/mkpart.rs
crates/disk-ops/src/resize.rs
crates/disks/src/config/disk.rs
crates/disks/src/config/disks.rs
crates/disks/src/config/lvm/mod.rs
crates/disks/src/config/partitions/mod.rs
crates/disks/src/error.rs
crates/hardware/src/switchable_graphics.rs
crates/locales/src/main_countries.rs
crates/squashfs/src/lib.rs
ffi/src/auto.rs
ffi/src/disk.rs
ffi/src/lib.rs
ffi/src/lvm.rs
ffi/src/partition.rs
ffi/src/sector.rs
ffi/src/timezones.rs
ffi/src/upgrade.rs
src/auto/options/apply.rs
src/installer/steps/configure/chroot_conf.rs
src/installer/steps/configure/mod.rs
src/lib.rs
src/upgrade.rs

Fix most warnings reported by compiling and clippy.
Rebase and squash when accepted.

Fix warnings

---

crates/hardware/src/switchable_graphics.rs

Follow up to #237 
Requires: pop-os/system76-power#204

Call PowerDaemon to determine default graphics mode

---

crates/locales/src/iso_codes.rs

fix: Hardcode a country name for Taiwan

---

cli/src/main.rs
ffi/distinst.vapi
ffi/src/config.rs
src/installer/mod.rs
src/installer/steps/configure/chroot_conf.rs
src/installer/steps/configure/mod.rs

Required by https://github.com/pop-os/installer/pull/219

feat: Support setting profile icon

---

src/auto/options/mod.rs
src/installer/steps/configure/chroot_conf.rs

feat: Allow refresh installs to any version of Linux

---

crates/disks/src/config/disks.rs

Handle disk sector size correctly

---

crates/hardware/examples/print-packages.rs
crates/hardware/src/lib.rs

The package needs to be in the ISO package pool (https://github.com/pop-os/iso/pull/299) for this to work.
Not sure the easiest way to test this...

Install `pop-hp-vendor` on Dev One, for Pop!_OS >= 22.04

---

src/installer/steps/configure/chroot_conf.rs

PR for testing changes to resolve issues seen in Trubble.

chore: Permit logs from apt to be reported when installing packages

---

src/distribution/debian.rs

Use HWE kernel for Ubuntu 22.04

---

src/installer/steps/configure/chroot_conf.rs

With Ubuntu Noble (24.04) based images, we get the following and the install fails:
```
log: INFO: configuring keyboard layout
log: INFO: running DEBIAN_FRONTEND="noninteractive" HOME="/root" LC_ALL="en_US.UTF-8" PATH="/usr/sbin:/usr/bin:/sbin:/bin" "chroot" "/tmp/distinst.KccLvDD3OjnV" "localectl" "set-x11-keymap" "us" "" ""
log: WARN: Setting X11 and console keymaps is not supported in Debian.
log: ERROR: configuring chroot error: error setting keyboard layout: command failed with exit status: exit status: 1
```
See https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2030788
Essentially `localectl` no longer supports setting keyboard config in Debian and Ubuntu. 
So, we change to writing the keyboard config to `/etc/default/keyboard` instead.
I've tested this with elementary OS …

chroot_conf: Write keyboard layout directly, avoiding localectl

---

crates/hardware/src/switchable_graphics.rs

Reverts pop-os/distinst#338
Replaces #340

Revert "fix(hardware): default to hybrid graphics on switchable systems"
